export 'package:medapp_eksad/widget/button_appbar.dart';
export 'package:medapp_eksad/widget/button_color.dart';
export 'package:medapp_eksad/widget/drawer.dart';
export 'package:medapp_eksad/widget/image_slide.dart';
export 'package:medapp_eksad/widget/responsive.dart';
export 'package:medapp_eksad/widget/whatsapp.dart';
export 'package:medapp_eksad/appbar/appbar_home.dart';
export 'package:medapp_eksad/screen/footer.dart';
export 'package:medapp_eksad/screen/solution.dart';
export 'package:medapp_eksad/screen/solution/our_solution.dart';
export 'package:medapp_eksad/screen/solution/our_solution2.dart';
export 'package:medapp_eksad/screen/contact_us/contact_us1.dart';
export 'package:medapp_eksad/screen/contact_us/contact_us2.dart';
export 'package:medapp_eksad/screen_small/small_footer.dart';
export 'package:medapp_eksad/screen_small/small_contact/small_contact_us1.dart';
export 'package:medapp_eksad/screen_small/small_contact/small_contact_us2.dart';
export 'package:medapp_eksad/screen_small/small_home/small_home1.dart';
export 'package:medapp_eksad/screen_small/small_home/small_home2.dart';
export 'package:medapp_eksad/screen_small/small_home/small_home3.dart';
export 'package:medapp_eksad/animation/animasi_kanan_kiri.dart';
export 'package:medapp_eksad/animation/animasi_kiri_kanan.dart';
export 'package:medapp_eksad/animation/kanan_kiri_small.dart';
export 'package:medapp_eksad/animation/kiri_kanan_small.dart';
String varA ='';
String varB ='';
String varC ='';
String varD ='';
String varE ='';
String varF ='';
