// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDrwgOX2lBl3oL3kSa4eTPZ2gdSUEA2i8',
    appId: '1:806811359126:web:59e4146f3da9eea2336fb7',
    messagingSenderId: '806811359126',
    projectId: 'medapp-by-eksad',
    authDomain: 'medapp-by-eksad.firebaseapp.com',
    storageBucket: 'medapp-by-eksad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwbsx4RbqVDPIMfESYw4NIaUCxedQpxHE',
    appId: '1:806811359126:android:30acc5ba52e4ec63336fb7',
    messagingSenderId: '806811359126',
    projectId: 'medapp-by-eksad',
    storageBucket: 'medapp-by-eksad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHUTLqbVYsWtQoVmP99KMNSoYhi2jVR3s',
    appId: '1:806811359126:ios:e456f4efc64e458d336fb7',
    messagingSenderId: '806811359126',
    projectId: 'medapp-by-eksad',
    storageBucket: 'medapp-by-eksad.appspot.com',
    iosClientId: '806811359126-32g1e7m46rra6sjidfah3fauor5sq511.apps.googleusercontent.com',
    iosBundleId: 'com.example.medappEksad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHUTLqbVYsWtQoVmP99KMNSoYhi2jVR3s',
    appId: '1:806811359126:ios:e456f4efc64e458d336fb7',
    messagingSenderId: '806811359126',
    projectId: 'medapp-by-eksad',
    storageBucket: 'medapp-by-eksad.appspot.com',
    iosClientId: '806811359126-32g1e7m46rra6sjidfah3fauor5sq511.apps.googleusercontent.com',
    iosBundleId: 'com.example.medappEksad',
  );
}
